### ISSUE TITLE
the sample code doesn`t work

### ISSUE THREAD

**Issue by advaithm** [opendnd/opendnd#4]
running the example code returns this
```
const name = Nomina.generate();
                    ^

TypeError: Nomina.generate is not a function
    at Object.<anonymous> (/home/advaithm/Desktop/dice/index.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```
running dnd dna give this error
```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '/usr/lib/node_modules/opendnd/node_modules/genetica/lib/Genetica'
Require stack:
- /usr/lib/node_modules/opendnd/node_modules/genetica/lib/program-generate.js
- /usr/lib/node_modules/opendnd/bin/dnd-dna-generate
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/lib/node_modules/opendnd/node_modules/genetica/lib/program-generate.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/opendnd/node_modules/genetica/lib/program-generate.js',
    '/usr/lib/node_modules/opendnd/bin/dnd-dna-generate'
  ]
}
```

**Comment by drewry** [comment]
@advaithm you are correct, we will update the sample code. Some changes were made to how the sub-packages are invoked and the sample code was not updated to reflect those changes.

**Comment by drewry** [comment]
@advaithm okay just pushed out a fix to the readme also updated the tests to check through the sample code 421286ee288a03267259f5944770036deda97396 and version 0.5.2 is on NPM now. Please give it a test when you can. Thank you for reporting your issue!

**Comment by advaithm** [comment]
i can confirm that as of writing the sample code works again
