### ISSUE TITLE
dnd dna is broken

### ISSUE THREAD

**Issue by advaithm** [opendnd/opendnd#5]
using the cli command ```dnd dan``` results in the following error
```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '/usr/lib/node_modules/opendnd/node_modules/genetica/lib/Genetica'
Require stack:
- /usr/lib/node_modules/opendnd/node_modules/genetica/lib/program-generate.js
- /usr/lib/node_modules/opendnd/bin/dnd-dna-generate
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/lib/node_modules/opendnd/node_modules/genetica/lib/program-generate.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/opendnd/node_modules/genetica/lib/program-generate.js',
    '/usr/lib/node_modules/opendnd/bin/dnd-dna-generate'
  ]
}
```

**Comment by drewry** [comment]
I see the issue. Can you try version opendnd@0.5.3?

**Comment by Lunarequest** [comment]
same error
```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '/usr/lib/node_modules/opendnd/node_modules/genetica/lib/Genetica'
Require stack:
- /usr/lib/node_modules/opendnd/node_modules/genetica/lib/program-generate.js
- /usr/lib/node_modules/opendnd/bin/dnd-dna-generate
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/lib/node_modules/opendnd/node_modules/genetica/lib/program-generate.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/opendnd/node_modules/genetica/lib/program-generate.js',
    '/usr/lib/node_modules/opendnd/bin/dnd-dna-generate'
  ]
}
```

**Comment by drewry** [comment]
@advaithm so the fact that it's looking for `/usr/lib/node_modules/opendnd/node_modules/genetica/lib/program-generate.js` instead of `/usr/lib/node_modules/opendnd/node_modules/@opendnd/genetica/dist/program-generate.js` means it is still using an older version. We recently moved to a new namespace on NPM for new packages being put under the @opendnd/{package-name}. 

Could you try uninstalling and reinstalling making sure you are getting version 0.5.3?

**Comment by Lunarequest** [comment]
Yeah sure
